INSERT INTO ATTENDEE (FIRST_NAME,LAST_NAME) VALUES ('THOMAS','NIELD');

INSERT INTO ATTENDEE (FIRST_NAME,LAST_NAME,PHONE,EMAIL,VIP) VALUES
    ('JON','SKEETER',4802185842,'JONH.SKEETER@REX.NET',1),
    ('SAM','SCALA',2156783401,'SAM.SCALA@GMAIL.COM',0),
    ('BRITTANY','FISHER',5932857296,'BRITTANY.FISHER@OUTLOOK.COM',0);

SELECT *
FROM ATTENDEE;

-- INSERTA EN LA TABLA ATTENDE EL RESULTADO DE UNA CONSULTA
INSERT INTO ATTENDEE (FIRST_NAME,LAST_NAME,PHONE,EMAIL)
SELECT FIRST_NAME,LAST_NAME,PHONE,EMAIL
FROM ATTENDEE
WHERE ATTENDEE_ID = 4;

INSERT INTO COMPANY (NAME,DESCRIPTION,PRIMARY_CONTACT_ATTENDEE_ID)
    VALUES ('REXAPP SOLUTIONS','A MOBILE APP DELIVERY SERVICE',3);

SELECT *
FROM COMPANY;

DELETE FROM ATTENDE
WHERE PHONE IS NULL AND EMAIL IS NULL;